server.port=${PORT:8081}
spring.application.name=customer-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:customerdb;DB_CLOSE_DELAY=-1;MODE=MySQL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
